const PRODUCTS = [
    {"id":1,"name":"Beef - Short Ribs","price":3.17,"amount":10},
    {"id":2,"name":"Jameson Irish Whiskey","price":14.57,"amount":3},
    {"id":3,"name":"Spice - Onion Powder Granulated","price":2.5,"amount":6},
    {"id":4,"name":"Ham - Cooked Italian","price":19.72,"amount":1},
    {"id":5,"name":"Dr. Pepper - 355ml","price":5.8,"amount":3},
    {"id":6,"name":"Turkey - Whole, Fresh","price":15.56,"amount":8},
    {"id":7,"name":"Nantucket - Orange Mango Cktl","price":9.04,"amount":9},
    {"id":8,"name":"Jam - Blackberry, 20 Ml Jar","price":18.26,"amount":2},
    {"id":9,"name":"Beans - Fine","price":15.64,"amount":9},
    {"id":10,"name":"Mushroom - Crimini","price":10.3,"amount":5},
    {"id":11,"name":"Pork - Tenderloin, Frozen","price":12.76,"amount":10},
    {"id":12,"name":"Lobster - Canned Premium","price":8.85,"amount":10},
    {"id":13,"name":"Tomato Puree","price":14.42,"amount":10},
    {"id":14,"name":"Cookies - Englishbay Wht","price":16.28,"amount":4},
    {"id":15,"name":"Sprouts - China Rose","price":4.2,"amount":6},
    {"id":16,"name":"Vinegar - White Wine","price":15.72,"amount":8},
    {"id":17,"name":"Beef - Bones, Marrow","price":17.96,"amount":3},
    {"id":18,"name":"Crush - Grape, 355 Ml","price":17.07,"amount":2},
    {"id":19,"name":"Galliano","price":13.7,"amount":1},
    {"id":20,"name":"Mussels - Cultivated","price":19.14,"amount":5},
    {"id":21,"name":"Tea - Lemon Green Tea","price":18.04,"amount":7},
    {"id":22,"name":"Garlic - Primerba, Paste","price":5.1,"amount":7},
    {"id":23,"name":"Cup - 4oz Translucent","price":4.15,"amount":1},
    {"id":24,"name":"Squash - Butternut","price":11.09,"amount":1},
    {"id":25,"name":"Bread Bowl Plain","price":19.14,"amount":5},
    {"id":26,"name":"Ecolab Digiclean Mild Fm","price":19.85,"amount":5},
    {"id":27,"name":"Wine - Niagara Peninsula Vqa","price":9.89,"amount":9},
    {"id":28,"name":"Cake - Dulce De Leche","price":18.45,"amount":3},
    {"id":29,"name":"Breadfruit","price":14.58,"amount":8},
    {"id":30,"name":"Wine - Dubouef Macon - Villages","price":13.79,"amount":2},
    {"id":31,"name":"Straws - Cocktale","price":10.02,"amount":5},
    {"id":32,"name":"Nacho Chips","price":2.29,"amount":3},
    {"id":33,"name":"Tuna - Loin","price":2.51,"amount":1},
    {"id":34,"name":"Cabbage - Red","price":7.35,"amount":6},
    {"id":35,"name":"Mushroom - Porcini, Dry","price":7.93,"amount":6},
    {"id":36,"name":"Chicken - Whole Fryers","price":10.6,"amount":6},
    {"id":37,"name":"Cheese - Parmigiano Reggiano","price":14.68,"amount":8},
    {"id":38,"name":"Cheese - Brie, Cups 125g","price":7.49,"amount":1},
    {"id":39,"name":"Salmon Steak - Cohoe 8 Oz","price":10.27,"amount":3},
    {"id":40,"name":"Table Cloth 144x90 White","price":2.85,"amount":6},
    {"id":41,"name":"Halibut - Fletches","price":4.55,"amount":3},
    {"id":42,"name":"Blueberries - Frozen","price":6.22,"amount":4},
    {"id":43,"name":"Salad Dressing","price":17.41,"amount":3},
    {"id":44,"name":"Juice - Pineapple, 48 Oz","price":18.21,"amount":6},
    {"id":45,"name":"Salt - Rock, Course","price":15.68,"amount":2},
    {"id":46,"name":"Wine - Ice Wine","price":17.99,"amount":2},
    {"id":47,"name":"Nantuket Peach Orange","price":9.08,"amount":1},
    {"id":48,"name":"Longos - Chicken Curried","price":10.09,"amount":5},
    {"id":49,"name":"Filter - Coffee","price":3.71,"amount":5},
    {"id":50,"name":"Puree - Passion Fruit","price":7.5,"amount":2}
]