const PROVINCIAS = [ 
    { idProvincia: "01", nombre: "Álava/Araba"},
    { idProvincia: "02", nombre: "Albacete"},
    { idProvincia: "03", nombre: "Alicante/Alacant"},
    { idProvincia: "04", nombre: "Almería"},
    { idProvincia: "33", nombre: "Asturias"},
    { idProvincia: "05", nombre: "Ávila"},
    { idProvincia: "06", nombre: "Badajoz"},
    { idProvincia: "07", nombre: "Balears (Illes)"},
    { idProvincia: "08", nombre: "Barcelona"},
    { idProvincia: "09", nombre: "Burgos"},
    { idProvincia: "10", nombre: "Cáceres"},
    { idProvincia: "11", nombre: "Cádiz"},
    { idProvincia: "39", nombre: "Cantabria"},
    { idProvincia: "12", nombre: "Castellón/Castelló"},
    { idProvincia: "51", nombre: "Ceuta"},
    { idProvincia: "13", nombre: "Ciudad Real"},
    { idProvincia: "14", nombre: "Córdoba"},
    { idProvincia: "15", nombre: "Coruña (A)"},
    { idProvincia: "16", nombre: "Cuenca"},
    { idProvincia: "17", nombre: "Girona"},
    { idProvincia: "18", nombre: "Granada"},
    { idProvincia: "19", nombre: "Guadalajara"},
    { idProvincia: "20", nombre: "Guipúzcoa/Gipuzkoa"},
    { idProvincia: "21", nombre: "Huelva"},
    { idProvincia: "22", nombre: "Huesca"},
    { idProvincia: "23", nombre: "Jaén"},
    { idProvincia: "24", nombre: "León"},
    { idProvincia: "27", nombre: "Lugo"},
    { idProvincia: "25", nombre: "Lleida"},
    { idProvincia: "28", nombre: "Madrid"},
    { idProvincia: "29", nombre: "Málaga"},
    { idProvincia: "52", nombre: "Melilla"},
    { idProvincia: "30", nombre: "Murcia"},
    { idProvincia: "31", nombre: "Navarra"},
    { idProvincia: "32", nombre: "Ourense"},
    { idProvincia: "34", nombre: "Palencia"},
    { idProvincia: "35", nombre: "Palmas (Las)"},
    { idProvincia: "36", nombre: "Pontevedra"},
    { idProvincia: "26", nombre: "Rioja (La)"},
    { idProvincia: "37", nombre: "Salamanca"},
    { idProvincia: "38", nombre: "Santa Cruz de Tenerife"},
    { idProvincia: "40", nombre: "Segovia"},
    { idProvincia: "41", nombre: "Sevilla"},
    { idProvincia: "42", nombre: "Soria"},
    { idProvincia: "43", nombre: "Tarragona"},
    { idProvincia: "44", nombre: "Teruel"},
    { idProvincia: "45", nombre: "Toledo"},
    { idProvincia: "46", nombre: "Valencia/València"},
    { idProvincia: "47", nombre: "Valladolid"},
    { idProvincia: "48", nombre: "Vizcaya/Bizkaia"},
    { idProvincia: "49", nombre: "Zamora"},
    { idProvincia: "50", nombre: "Zaragoza"},
];


